#ifndef MACRO_CONFIG_INT
#error "The config macros must be defined"
#define MACRO_CONFIG_INT(Name, ScriptName, Def, Min, Max, Flags, Desc) ;
#define MACRO_CONFIG_COL(Name, ScriptName, Def, Flags, Desc) ;
#define MACRO_CONFIG_STR(Name, ScriptName, Len, Def, Flags, Desc) ;
#endif

MACRO_CONFIG_INT(CcAutoTeamLock, cc_auto_team_lock, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically lock your team after joining it")
MACRO_CONFIG_INT(CcAutoTeamLockDelay, cc_auto_team_lock_delay, 0, 0, 60, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How many seconds to wait before automatically locking your team")
MACRO_CONFIG_INT(CcAntiQuit, cc_anti_quit, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Always show a confirmation popup before quitting the client")
MACRO_CONFIG_STR(CcFirstRun, first_run, 16, "true", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Whether the CatClient first-run setup should be shown")
MACRO_CONFIG_INT(CcServerBrowserAutoRefresh, cc_server_browser_auto_refresh, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically refresh the current server browser tab")
MACRO_CONFIG_INT(CcServerBrowserRefreshInterval, cc_server_browser_refresh_interval, 5, 1, 30, CFGFLAG_CLIENT | CFGFLAG_SAVE, "How often to automatically refresh the current server browser tab, in seconds")
MACRO_CONFIG_INT(CcBrFilterCatClient, cc_br_filter_catclient, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show only servers where CatClient users are currently online")
MACRO_CONFIG_INT(CcShopAutoSet, cc_shop_auto_set, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically apply shop assets after downloading them")
MACRO_CONFIG_INT(CcAspectRatioEnabled, cc_aspect_ratio_enabled, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Apply a custom stretched aspect ratio to ingame rendering")
MACRO_CONFIG_INT(CcAspectRatio, cc_aspect_ratio, 177, 100, 400, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom ingame aspect ratio multiplied by 100, e.g. 177 means 1.77")
MACRO_CONFIG_INT(CcAspectRatioCustom, cc_aspect_ratio_custom, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use separate width and height inputs for the ingame stretched aspect ratio")
MACRO_CONFIG_INT(CcAspectRatioCustomX, cc_aspect_ratio_custom_x, 1920, 1, 100000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio width input, e.g. 1920")
MACRO_CONFIG_INT(CcAspectRatioCustomY, cc_aspect_ratio_custom_y, 1080, 1, 100000, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom aspect ratio height input, e.g. 1080")
MACRO_CONFIG_INT(CcAspectRatioExclude, cc_aspect_ratio_exclude_hud, 1, 0, 7, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bitmask of ingame UI elements to render without the custom aspect ratio stretch")
MACRO_CONFIG_INT(CcUiScale, cc_ui_scale, 100, 50, 100, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Scale the menu UI in percent, where 100 is the default size")
MACRO_CONFIG_INT(CcNewMainMenu, cc_new_main_menu, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the start menu in the compact CatClient layout")
MACRO_CONFIG_INT(CcCustomBackgroundMainMenu, cc_custom_background_main_menu, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the selected custom background image in the main menu")
MACRO_CONFIG_INT(CcCustomBackgroundGame, cc_custom_background_game, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the selected custom background image ingame behind the world")
MACRO_CONFIG_STR(CcCustomBackgroundImage, cc_custom_background_image, 128, "firstbg.jpg", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Selected custom background image filename inside catclient/backgrounds")
MACRO_CONFIG_INT(CcEnhancedLaser, cc_enhanced_laser, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Use CatClient enhanced laser rendering")
MACRO_CONFIG_INT(CcMuteSounds, cc_mute_sounds, 0, 0, 31, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bitmask of CatClient sound muting options")
MACRO_CONFIG_INT(CcHideEffects, cc_hide_effects, 0, 0, 7, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bitmask of CatClient effect hiding options")
MACRO_CONFIG_INT(CcChatAnimations, cc_chat_animations, 0, 0, 3, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bitmask of CatClient chat animation options")
MACRO_CONFIG_INT(CcModernUi, cc_modern_ui, 8, 0, 11, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bitmask of CatClient modern UI widgets")
MACRO_CONFIG_INT(CcHorizontalSettingsTabs, cc_horizontal_settings_tabs, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show the main settings tabs in a horizontal top bar")
MACRO_CONFIG_INT(CcStreamerMode, cc_streamer_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable CatClient streamer mode")
MACRO_CONFIG_INT(CcStreamerFlags, cc_streamer_flags, 0, 0, 7, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Bitmask of CatClient streamer mode options")

MACRO_CONFIG_INT(BcVoiceChatEnable, bc_voice_chat_enable, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable integrated voice chat")
MACRO_CONFIG_INT(BcVoiceChatActivationMode, bc_voice_chat_activation_mode, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice activation mode (0 = automatic activation, 1 = push-to-talk)")
MACRO_CONFIG_INT(BcVoiceChatVolume, bc_voice_chat_volume, 100, 0, 200, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice playback volume in percent")
MACRO_CONFIG_INT(BcVoiceChatMicGain, bc_voice_chat_mic_gain, 100, 0, 300, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Microphone gain in percent")
MACRO_CONFIG_INT(BcVoiceChatBitrate, bc_voice_chat_bitrate, 96, 6, 96, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice Opus bitrate in kbps")
MACRO_CONFIG_INT(BcVoiceChatInputDevice, bc_voice_chat_input_device, -1, -1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice input device index (-1 = system default)")
MACRO_CONFIG_INT(BcVoiceChatOutputDevice, bc_voice_chat_output_device, -1, -1, 64, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice output device index (-1 = system default)")
MACRO_CONFIG_INT(BcVoiceChatMicMuted, bc_voice_chat_mic_muted, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute voice microphone")
MACRO_CONFIG_INT(BcVoiceChatHeadphonesMuted, bc_voice_chat_headphones_muted, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Mute voice playback")
MACRO_CONFIG_INT(BcVoiceChatMicCheck, bc_voice_chat_mic_check, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Enable microphone check (local loopback)")
MACRO_CONFIG_INT(BcVoiceChatNameplateIcon, bc_voice_chat_nameplate_icon, 1, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Show microphone icon in name plates for talking players")
MACRO_CONFIG_STR(BcVoiceChatServerAddress, bc_voice_chat_server_address, 128, "127.0.0.1:8777", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Voice server address")
MACRO_CONFIG_STR(BcVoiceChatMutedNames, bc_voice_chat_muted_names, 512, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Comma-separated list of muted voice nicknames (case-insensitive)")
MACRO_CONFIG_STR(BcVoiceChatNameVolumes, bc_voice_chat_name_volumes, 512, "", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Comma-separated list of voice nickname volumes in percent (name=value, case-insensitive)")

MACRO_CONFIG_INT(CcAutoLagMessage, cc_auto_lag_message, 0, 0, 1, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Automatically send a message when experiencing lag")
MACRO_CONFIG_STR(CcAutoLagMessageText, cc_auto_lag_message_text, 128, "lag", CFGFLAG_CLIENT | CFGFLAG_SAVE, "Custom message to send when experiencing lag")
MACRO_CONFIG_INT(CcAutoLagMessagePing, cc_auto_lag_message_ping, 200, 100, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Minimum ping threshold in milliseconds to trigger lag message")
MACRO_CONFIG_INT(CcAutoLagMessageThreshold, cc_auto_lag_message_threshold, 200, 100, 500, CFGFLAG_CLIENT | CFGFLAG_SAVE, "Frame time threshold in milliseconds to detect real game lag")
