variables:
  - &fast_build_env
    environment:
      CARGO_HTTP_MULTIPLEXING: "false"

when:
  - event: push
    branch:
      exclude:
        - gh-readonly-queue/**
  - event: manual

labels:
  platform: darwin

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  build-macos:
    image: bash
    <<: *fast_build_env
    commands:
      - brew update || true
      - brew install pkg-config ninja molten-vk vulkan-headers glslang spirv-tools glew googletest libpng molten-vk opusfile wavpack x264 libjpeg || true
      - brew upgrade freetype
      - pip3 install --break-system-packages dmgbuild
      - rustup default stable
      - rustup update
      - rustup target add x86_64-apple-darwin aarch64-apple-darwin
      - rm -rf /Library/Developer/CommandLineTools || true
      - mkdir -p release
      - cd release
      - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DDISCORD=ON -DWEBSOCKETS=OFF -DPREFER_BUNDLED_LIBS=ON -DCMAKE_OSX_ARCHITECTURES=arm64 -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 -DCMAKE_SYSTEM_IGNORE_PATH=/usr/lib -DCMAKE_FIND_FRAMEWORK=LAST -DAUTOUPDATE=OFF -DPNG_LIBRARY="$CI_WORKSPACE/ddnet-libs/png/mac/libfat/libpng16.16.dylib" -DPNG_INCLUDEDIR="$CI_WORKSPACE/ddnet-libs/png/include" -DDOWNLOAD_GTEST=ON -DCMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE=. ..
      - cmake --build . --config Release --target everything
      - cmake --build . --config Release --target package_default
